.Dd November 13, 2017
.Dt LUMINA-FILEINFO 8
.Os 1.3.3

.Sh NAME
.Nm lumina-fileinfo
.Nd views properties of files.
Includes creator for XDG application registrations and XDG-compliant
desktop entries.

.Sh SYNOPSIS
.Nm

.Sh DESCRIPTION
.Nm
displays a graphical utility to create XDG-compliant desktop entries.
.Nm
also views file properties.
It shows properties including: type, mimetype, file size, owner,
group, permissions, date created, and date of last modification.


.Sh EXAMPLES
.Bl -tag -width indent
.It lumina-fileinfo /usr/home/aaron/Downloads/Testing.png
Opens the utility and shows detailed information about Testing.png
.El

.Sh AUTHORS
.An Aaron St. John and Tim Moore
.Aq aaron@ixsystems.com
