Summary:            A lightweight, portable desktop environment
Name:               lumina-desktop
Version:            0.8.5
Release:            1%{?dist}
License:            BSD
Group:              System Environment/Base
Source:             http://ftp.lumina-desktop.org/lumina-desktop-0.8.5.tar.gz
URL:                http://lumina-desktop.org
ExcludeArch:        s390 s390x
BuildRequires:      gcc, gcc-c++, qt-devel, qt-config, qt5-qttools, qt5-qttools-devel, qt5-qtbase-gui, qt5-qtmultimedia-devel, qt5-qtsvg-devel, qt5-qtx11extras-devel, xcb-util-image, xcb-util-image-devel, xcb-util-wm-devel, libxcb-devel, xcb-util-devel, phonon-devel, phonon-qt5-devel, libXcomposite-devel, libXdamage-devel, libXrender-devel, qt5-qtdeclarative-devel
Requires: qt5-style-oxygen, plasma-oxygen, xscreensaver, xbacklight, alsa-utils, acpi, numlockx, pavucontrol, xterm 

%description
The Lumina Desktop Environment is a lightweight system interface that is designed for use on any Unix-like operating system. 

%prep
%autosetup -n lumina

%build
qmake-qt5 INSTALL_ROOT=%{buildroot} PREFIX=/usr/local LIBPREFIX=/lib64

%install
# %make_install
make INSTALL_ROOT=%{buildroot} PREFIX=/usr/local LIBPREFIX=/lib64 install

%files
/usr/local/bin/Lumina-DE
/usr/local/bin/lumina-open
/usr/local/bin/lumina-config
/usr/local/bin/lumina-fm
/usr/local/bin/lumina-screenshot
/usr/local/bin/lumina-search
/usr/local/bin/lumina-info
/usr/local/bin/lumina-xconfig
/usr/local/bin/lumina-fileinfo
/usr/local/etc/luminaDesktop.conf.dist
/lib64/libLuminaUtils.so
/lib64/libLuminaUtils.so.1
/lib64/libLuminaUtils.so.1.0
/lib64/libLuminaUtils.so.1.0.0
/usr/local/include/LuminaXDG.h
/usr/local/include/LuminaUtils.h
/usr/local/include/LuminaX11.h
/usr/local/include/LuminaThemes.h
/usr/local/include/LuminaOS.h
/usr/local/include/LuminaSingleApplication.h
/usr/local/share/applications/lumina-fm.desktop
/usr/local/share/applications/lumina-screenshot.desktop
/usr/local/share/applications/lumina-search.desktop
/usr/local/share/applications/lumina-info.desktop
/usr/local/share/pixmaps/Lumina-DE.png
/usr/local/share/pixmaps/Insight-FileManager.png
/usr/share/xsessions/Lumina-DE.desktop
/usr/local/share/Lumina-DE/desktop-background.jpg
/usr/local/share/Lumina-DE/defaultapps.conf
/usr/local/share/Lumina-DE/luminaDesktop.conf
/usr/local/share/Lumina-DE/fluxbox-init-rc
/usr/local/share/Lumina-DE/fluxbox-keys
/usr/local/share/Lumina-DE/Login.ogg
/usr/local/share/Lumina-DE/Logout.ogg
/usr/local/share/Lumina-DE/colors/Lumina-Red.qss.colors
/usr/local/share/Lumina-DE/colors/Lumina-Green.qss.colors
/usr/local/share/Lumina-DE/colors/Lumina-Purple.qss.colors
/usr/local/share/Lumina-DE/colors/Lumina-Gold.qss.colors
/usr/local/share/Lumina-DE/colors/Lumina-Glass.qss.colors
/usr/local/share/Lumina-DE/colors/PCBSD10-Default.qss.colors
/usr/local/share/Lumina-DE/themes/Lumina-default.qss.template
/usr/local/share/Lumina-DE/themes/None.qss.template
/usr/local/share/Lumina-DE/quickplugins/quick-sample.qml
/usr/local/share/wallpapers/Lumina-DE/Lumina_Wispy_gold_1920x1080.jpg
/usr/local/share/wallpapers/Lumina-DE/Lumina_Wispy_green_1920x1080.jpg
/usr/local/share/wallpapers/Lumina-DE/Lumina_Wispy_purple_1920x1080.jpg
/usr/local/share/wallpapers/Lumina-DE/Lumina_Wispy_red_1920x1080.jpg
/usr/local/share/Lumina-DE/i18n/lumina-config_af.qm
/usr/local/share/Lumina-DE/i18n/lumina-config_ar.qm
/usr/local/share/Lumina-DE/i18n/lumina-config_az.qm
/usr/local/share/Lumina-DE/i18n/lumina-config_bg.qm
/usr/local/share/Lumina-DE/i18n/lumina-config_bn.qm
/usr/local/share/Lumina-DE/i18n/lumina-config_bs.qm
/usr/local/share/Lumina-DE/i18n/lumina-config_ca.qm
/usr/local/share/Lumina-DE/i18n/lumina-config_cs.qm
/usr/local/share/Lumina-DE/i18n/lumina-config_cy.qm
/usr/local/share/Lumina-DE/i18n/lumina-config_da.qm
/usr/local/share/Lumina-DE/i18n/lumina-config_de.qm
/usr/local/share/Lumina-DE/i18n/lumina-config_el.qm
/usr/local/share/Lumina-DE/i18n/lumina-config_en_GB.qm
/usr/local/share/Lumina-DE/i18n/lumina-config_en_ZA.qm
/usr/local/share/Lumina-DE/i18n/lumina-config_es.qm
/usr/local/share/Lumina-DE/i18n/lumina-config_et.qm
/usr/local/share/Lumina-DE/i18n/lumina-config_eu.qm
/usr/local/share/Lumina-DE/i18n/lumina-config_fa.qm
/usr/local/share/Lumina-DE/i18n/lumina-config_fi.qm
/usr/local/share/Lumina-DE/i18n/lumina-config_fr.qm
/usr/local/share/Lumina-DE/i18n/lumina-config_fr_CA.qm
/usr/local/share/Lumina-DE/i18n/lumina-config_gl.qm
/usr/local/share/Lumina-DE/i18n/lumina-config_he.qm
/usr/local/share/Lumina-DE/i18n/lumina-config_hi.qm
/usr/local/share/Lumina-DE/i18n/lumina-config_hr.qm
/usr/local/share/Lumina-DE/i18n/lumina-config_hu.qm
/usr/local/share/Lumina-DE/i18n/lumina-config_id.qm
/usr/local/share/Lumina-DE/i18n/lumina-config_is.qm
/usr/local/share/Lumina-DE/i18n/lumina-config_it.qm
/usr/local/share/Lumina-DE/i18n/lumina-config_ja.qm
/usr/local/share/Lumina-DE/i18n/lumina-config_ka.qm
/usr/local/share/Lumina-DE/i18n/lumina-config_ko.qm
/usr/local/share/Lumina-DE/i18n/lumina-config_lt.qm
/usr/local/share/Lumina-DE/i18n/lumina-config_lv.qm
/usr/local/share/Lumina-DE/i18n/lumina-config_mk.qm
/usr/local/share/Lumina-DE/i18n/lumina-config_mn.qm
/usr/local/share/Lumina-DE/i18n/lumina-config_ms.qm
/usr/local/share/Lumina-DE/i18n/lumina-config_mt.qm
/usr/local/share/Lumina-DE/i18n/lumina-config_nb.qm
/usr/local/share/Lumina-DE/i18n/lumina-config_nl.qm
/usr/local/share/Lumina-DE/i18n/lumina-config_pa.qm
/usr/local/share/Lumina-DE/i18n/lumina-config_pl.qm
/usr/local/share/Lumina-DE/i18n/lumina-config_pt.qm
/usr/local/share/Lumina-DE/i18n/lumina-config_pt_BR.qm
/usr/local/share/Lumina-DE/i18n/lumina-config_ro.qm
/usr/local/share/Lumina-DE/i18n/lumina-config_ru.qm
/usr/local/share/Lumina-DE/i18n/lumina-config_sk.qm
/usr/local/share/Lumina-DE/i18n/lumina-config_sl.qm
/usr/local/share/Lumina-DE/i18n/lumina-config_sr.qm
/usr/local/share/Lumina-DE/i18n/lumina-config_sv.qm
/usr/local/share/Lumina-DE/i18n/lumina-config_sw.qm
/usr/local/share/Lumina-DE/i18n/lumina-config_ta.qm
/usr/local/share/Lumina-DE/i18n/lumina-config_tg.qm
/usr/local/share/Lumina-DE/i18n/lumina-config_th.qm
/usr/local/share/Lumina-DE/i18n/lumina-config_tr.qm
/usr/local/share/Lumina-DE/i18n/lumina-config_uk.qm
/usr/local/share/Lumina-DE/i18n/lumina-config_uz.qm
/usr/local/share/Lumina-DE/i18n/lumina-config_vi.qm
/usr/local/share/Lumina-DE/i18n/lumina-config_zh_CN.qm
/usr/local/share/Lumina-DE/i18n/lumina-config_zh_HK.qm
/usr/local/share/Lumina-DE/i18n/lumina-config_zh_TW.qm
/usr/local/share/Lumina-DE/i18n/lumina-config_zu.qm
/usr/local/share/Lumina-DE/i18n/lumina-desktop_af.qm
/usr/local/share/Lumina-DE/i18n/lumina-desktop_ar.qm
/usr/local/share/Lumina-DE/i18n/lumina-desktop_az.qm
/usr/local/share/Lumina-DE/i18n/lumina-desktop_bg.qm
/usr/local/share/Lumina-DE/i18n/lumina-desktop_bn.qm
/usr/local/share/Lumina-DE/i18n/lumina-desktop_bs.qm
/usr/local/share/Lumina-DE/i18n/lumina-desktop_ca.qm
/usr/local/share/Lumina-DE/i18n/lumina-desktop_cs.qm
/usr/local/share/Lumina-DE/i18n/lumina-desktop_cy.qm
/usr/local/share/Lumina-DE/i18n/lumina-desktop_da.qm
/usr/local/share/Lumina-DE/i18n/lumina-desktop_de.qm
/usr/local/share/Lumina-DE/i18n/lumina-desktop_el.qm
/usr/local/share/Lumina-DE/i18n/lumina-desktop_en_GB.qm
/usr/local/share/Lumina-DE/i18n/lumina-desktop_en_ZA.qm
/usr/local/share/Lumina-DE/i18n/lumina-desktop_es.qm
/usr/local/share/Lumina-DE/i18n/lumina-desktop_et.qm
/usr/local/share/Lumina-DE/i18n/lumina-desktop_eu.qm
/usr/local/share/Lumina-DE/i18n/lumina-desktop_fa.qm
/usr/local/share/Lumina-DE/i18n/lumina-desktop_fi.qm
/usr/local/share/Lumina-DE/i18n/lumina-desktop_fr.qm
/usr/local/share/Lumina-DE/i18n/lumina-desktop_fr_CA.qm
/usr/local/share/Lumina-DE/i18n/lumina-desktop_gl.qm
/usr/local/share/Lumina-DE/i18n/lumina-desktop_he.qm
/usr/local/share/Lumina-DE/i18n/lumina-desktop_hi.qm
/usr/local/share/Lumina-DE/i18n/lumina-desktop_hr.qm
/usr/local/share/Lumina-DE/i18n/lumina-desktop_hu.qm
/usr/local/share/Lumina-DE/i18n/lumina-desktop_id.qm
/usr/local/share/Lumina-DE/i18n/lumina-desktop_is.qm
/usr/local/share/Lumina-DE/i18n/lumina-desktop_it.qm
/usr/local/share/Lumina-DE/i18n/lumina-desktop_ja.qm
/usr/local/share/Lumina-DE/i18n/lumina-desktop_ka.qm
/usr/local/share/Lumina-DE/i18n/lumina-desktop_ko.qm
/usr/local/share/Lumina-DE/i18n/lumina-desktop_lt.qm
/usr/local/share/Lumina-DE/i18n/lumina-desktop_lv.qm
/usr/local/share/Lumina-DE/i18n/lumina-desktop_mk.qm
/usr/local/share/Lumina-DE/i18n/lumina-desktop_mn.qm
/usr/local/share/Lumina-DE/i18n/lumina-desktop_ms.qm
/usr/local/share/Lumina-DE/i18n/lumina-desktop_mt.qm
/usr/local/share/Lumina-DE/i18n/lumina-desktop_nb.qm
/usr/local/share/Lumina-DE/i18n/lumina-desktop_nl.qm
/usr/local/share/Lumina-DE/i18n/lumina-desktop_pa.qm
/usr/local/share/Lumina-DE/i18n/lumina-desktop_pl.qm
/usr/local/share/Lumina-DE/i18n/lumina-desktop_pt.qm
/usr/local/share/Lumina-DE/i18n/lumina-desktop_pt_BR.qm
/usr/local/share/Lumina-DE/i18n/lumina-desktop_ro.qm
/usr/local/share/Lumina-DE/i18n/lumina-desktop_ru.qm
/usr/local/share/Lumina-DE/i18n/lumina-desktop_sk.qm
/usr/local/share/Lumina-DE/i18n/lumina-desktop_sl.qm
/usr/local/share/Lumina-DE/i18n/lumina-desktop_sr.qm
/usr/local/share/Lumina-DE/i18n/lumina-desktop_sv.qm
/usr/local/share/Lumina-DE/i18n/lumina-desktop_sw.qm
/usr/local/share/Lumina-DE/i18n/lumina-desktop_ta.qm
/usr/local/share/Lumina-DE/i18n/lumina-desktop_tg.qm
/usr/local/share/Lumina-DE/i18n/lumina-desktop_th.qm
/usr/local/share/Lumina-DE/i18n/lumina-desktop_tr.qm
/usr/local/share/Lumina-DE/i18n/lumina-desktop_uk.qm
/usr/local/share/Lumina-DE/i18n/lumina-desktop_uz.qm
/usr/local/share/Lumina-DE/i18n/lumina-desktop_vi.qm
/usr/local/share/Lumina-DE/i18n/lumina-desktop_zh_CN.qm
/usr/local/share/Lumina-DE/i18n/lumina-desktop_zh_HK.qm
/usr/local/share/Lumina-DE/i18n/lumina-desktop_zh_TW.qm
/usr/local/share/Lumina-DE/i18n/lumina-desktop_zu.qm
/usr/local/share/Lumina-DE/i18n/lumina-fileinfo_af.qm
/usr/local/share/Lumina-DE/i18n/lumina-fileinfo_ar.qm
/usr/local/share/Lumina-DE/i18n/lumina-fileinfo_az.qm
/usr/local/share/Lumina-DE/i18n/lumina-fileinfo_bg.qm
/usr/local/share/Lumina-DE/i18n/lumina-fileinfo_bn.qm
/usr/local/share/Lumina-DE/i18n/lumina-fileinfo_bs.qm
/usr/local/share/Lumina-DE/i18n/lumina-fileinfo_ca.qm
/usr/local/share/Lumina-DE/i18n/lumina-fileinfo_cs.qm
/usr/local/share/Lumina-DE/i18n/lumina-fileinfo_cy.qm
/usr/local/share/Lumina-DE/i18n/lumina-fileinfo_da.qm
/usr/local/share/Lumina-DE/i18n/lumina-fileinfo_de.qm
/usr/local/share/Lumina-DE/i18n/lumina-fileinfo_el.qm
/usr/local/share/Lumina-DE/i18n/lumina-fileinfo_en_GB.qm
/usr/local/share/Lumina-DE/i18n/lumina-fileinfo_en_ZA.qm
/usr/local/share/Lumina-DE/i18n/lumina-fileinfo_es.qm
/usr/local/share/Lumina-DE/i18n/lumina-fileinfo_et.qm
/usr/local/share/Lumina-DE/i18n/lumina-fileinfo_eu.qm
/usr/local/share/Lumina-DE/i18n/lumina-fileinfo_fa.qm
/usr/local/share/Lumina-DE/i18n/lumina-fileinfo_fi.qm
/usr/local/share/Lumina-DE/i18n/lumina-fileinfo_fr.qm
/usr/local/share/Lumina-DE/i18n/lumina-fileinfo_fr_CA.qm
/usr/local/share/Lumina-DE/i18n/lumina-fileinfo_gl.qm
/usr/local/share/Lumina-DE/i18n/lumina-fileinfo_he.qm
/usr/local/share/Lumina-DE/i18n/lumina-fileinfo_hi.qm
/usr/local/share/Lumina-DE/i18n/lumina-fileinfo_hr.qm
/usr/local/share/Lumina-DE/i18n/lumina-fileinfo_hu.qm
/usr/local/share/Lumina-DE/i18n/lumina-fileinfo_id.qm
/usr/local/share/Lumina-DE/i18n/lumina-fileinfo_is.qm
/usr/local/share/Lumina-DE/i18n/lumina-fileinfo_it.qm
/usr/local/share/Lumina-DE/i18n/lumina-fileinfo_ja.qm
/usr/local/share/Lumina-DE/i18n/lumina-fileinfo_ka.qm
/usr/local/share/Lumina-DE/i18n/lumina-fileinfo_ko.qm
/usr/local/share/Lumina-DE/i18n/lumina-fileinfo_lt.qm
/usr/local/share/Lumina-DE/i18n/lumina-fileinfo_lv.qm
/usr/local/share/Lumina-DE/i18n/lumina-fileinfo_mk.qm
/usr/local/share/Lumina-DE/i18n/lumina-fileinfo_mn.qm
/usr/local/share/Lumina-DE/i18n/lumina-fileinfo_ms.qm
/usr/local/share/Lumina-DE/i18n/lumina-fileinfo_mt.qm
/usr/local/share/Lumina-DE/i18n/lumina-fileinfo_nb.qm
/usr/local/share/Lumina-DE/i18n/lumina-fileinfo_nl.qm
/usr/local/share/Lumina-DE/i18n/lumina-fileinfo_pa.qm
/usr/local/share/Lumina-DE/i18n/lumina-fileinfo_pl.qm
/usr/local/share/Lumina-DE/i18n/lumina-fileinfo_pt.qm
/usr/local/share/Lumina-DE/i18n/lumina-fileinfo_pt_BR.qm
/usr/local/share/Lumina-DE/i18n/lumina-fileinfo_ro.qm
/usr/local/share/Lumina-DE/i18n/lumina-fileinfo_ru.qm
/usr/local/share/Lumina-DE/i18n/lumina-fileinfo_sk.qm
/usr/local/share/Lumina-DE/i18n/lumina-fileinfo_sl.qm
/usr/local/share/Lumina-DE/i18n/lumina-fileinfo_sr.qm
/usr/local/share/Lumina-DE/i18n/lumina-fileinfo_sv.qm
/usr/local/share/Lumina-DE/i18n/lumina-fileinfo_sw.qm
/usr/local/share/Lumina-DE/i18n/lumina-fileinfo_ta.qm
/usr/local/share/Lumina-DE/i18n/lumina-fileinfo_tg.qm
/usr/local/share/Lumina-DE/i18n/lumina-fileinfo_th.qm
/usr/local/share/Lumina-DE/i18n/lumina-fileinfo_tr.qm
/usr/local/share/Lumina-DE/i18n/lumina-fileinfo_uk.qm
/usr/local/share/Lumina-DE/i18n/lumina-fileinfo_uz.qm
/usr/local/share/Lumina-DE/i18n/lumina-fileinfo_vi.qm
/usr/local/share/Lumina-DE/i18n/lumina-fileinfo_zh_CN.qm
/usr/local/share/Lumina-DE/i18n/lumina-fileinfo_zh_HK.qm
/usr/local/share/Lumina-DE/i18n/lumina-fileinfo_zh_TW.qm
/usr/local/share/Lumina-DE/i18n/lumina-fileinfo_zu.qm
/usr/local/share/Lumina-DE/i18n/lumina-fm_af.qm
/usr/local/share/Lumina-DE/i18n/lumina-fm_ar.qm
/usr/local/share/Lumina-DE/i18n/lumina-fm_az.qm
/usr/local/share/Lumina-DE/i18n/lumina-fm_bg.qm
/usr/local/share/Lumina-DE/i18n/lumina-fm_bn.qm
/usr/local/share/Lumina-DE/i18n/lumina-fm_bs.qm
/usr/local/share/Lumina-DE/i18n/lumina-fm_ca.qm
/usr/local/share/Lumina-DE/i18n/lumina-fm_cs.qm
/usr/local/share/Lumina-DE/i18n/lumina-fm_cy.qm
/usr/local/share/Lumina-DE/i18n/lumina-fm_da.qm
/usr/local/share/Lumina-DE/i18n/lumina-fm_de.qm
/usr/local/share/Lumina-DE/i18n/lumina-fm_el.qm
/usr/local/share/Lumina-DE/i18n/lumina-fm_en_GB.qm
/usr/local/share/Lumina-DE/i18n/lumina-fm_en_ZA.qm
/usr/local/share/Lumina-DE/i18n/lumina-fm_es.qm
/usr/local/share/Lumina-DE/i18n/lumina-fm_et.qm
/usr/local/share/Lumina-DE/i18n/lumina-fm_eu.qm
/usr/local/share/Lumina-DE/i18n/lumina-fm_fa.qm
/usr/local/share/Lumina-DE/i18n/lumina-fm_fi.qm
/usr/local/share/Lumina-DE/i18n/lumina-fm_fr.qm
/usr/local/share/Lumina-DE/i18n/lumina-fm_fr_CA.qm
/usr/local/share/Lumina-DE/i18n/lumina-fm_gl.qm
/usr/local/share/Lumina-DE/i18n/lumina-fm_he.qm
/usr/local/share/Lumina-DE/i18n/lumina-fm_hi.qm
/usr/local/share/Lumina-DE/i18n/lumina-fm_hr.qm
/usr/local/share/Lumina-DE/i18n/lumina-fm_hu.qm
/usr/local/share/Lumina-DE/i18n/lumina-fm_id.qm
/usr/local/share/Lumina-DE/i18n/lumina-fm_is.qm
/usr/local/share/Lumina-DE/i18n/lumina-fm_it.qm
/usr/local/share/Lumina-DE/i18n/lumina-fm_ja.qm
/usr/local/share/Lumina-DE/i18n/lumina-fm_ka.qm
/usr/local/share/Lumina-DE/i18n/lumina-fm_ko.qm
/usr/local/share/Lumina-DE/i18n/lumina-fm_lt.qm
/usr/local/share/Lumina-DE/i18n/lumina-fm_lv.qm
/usr/local/share/Lumina-DE/i18n/lumina-fm_mk.qm
/usr/local/share/Lumina-DE/i18n/lumina-fm_mn.qm
/usr/local/share/Lumina-DE/i18n/lumina-fm_ms.qm
/usr/local/share/Lumina-DE/i18n/lumina-fm_mt.qm
/usr/local/share/Lumina-DE/i18n/lumina-fm_nb.qm
/usr/local/share/Lumina-DE/i18n/lumina-fm_nl.qm
/usr/local/share/Lumina-DE/i18n/lumina-fm_pa.qm
/usr/local/share/Lumina-DE/i18n/lumina-fm_pl.qm
/usr/local/share/Lumina-DE/i18n/lumina-fm_pt.qm
/usr/local/share/Lumina-DE/i18n/lumina-fm_pt_BR.qm
/usr/local/share/Lumina-DE/i18n/lumina-fm_ro.qm
/usr/local/share/Lumina-DE/i18n/lumina-fm_ru.qm
/usr/local/share/Lumina-DE/i18n/lumina-fm_sk.qm
/usr/local/share/Lumina-DE/i18n/lumina-fm_sl.qm
/usr/local/share/Lumina-DE/i18n/lumina-fm_sr.qm
/usr/local/share/Lumina-DE/i18n/lumina-fm_sv.qm
/usr/local/share/Lumina-DE/i18n/lumina-fm_sw.qm
/usr/local/share/Lumina-DE/i18n/lumina-fm_ta.qm
/usr/local/share/Lumina-DE/i18n/lumina-fm_tg.qm
/usr/local/share/Lumina-DE/i18n/lumina-fm_th.qm
/usr/local/share/Lumina-DE/i18n/lumina-fm_tr.qm
/usr/local/share/Lumina-DE/i18n/lumina-fm_uk.qm
/usr/local/share/Lumina-DE/i18n/lumina-fm_uz.qm
/usr/local/share/Lumina-DE/i18n/lumina-fm_vi.qm
/usr/local/share/Lumina-DE/i18n/lumina-fm_zh_CN.qm
/usr/local/share/Lumina-DE/i18n/lumina-fm_zh_HK.qm
/usr/local/share/Lumina-DE/i18n/lumina-fm_zh_TW.qm
/usr/local/share/Lumina-DE/i18n/lumina-fm_zu.qm
/usr/local/share/Lumina-DE/i18n/lumina-info_af.qm
/usr/local/share/Lumina-DE/i18n/lumina-info_ar.qm
/usr/local/share/Lumina-DE/i18n/lumina-info_az.qm
/usr/local/share/Lumina-DE/i18n/lumina-info_bg.qm
/usr/local/share/Lumina-DE/i18n/lumina-info_bn.qm
/usr/local/share/Lumina-DE/i18n/lumina-info_bs.qm
/usr/local/share/Lumina-DE/i18n/lumina-info_ca.qm
/usr/local/share/Lumina-DE/i18n/lumina-info_cs.qm
/usr/local/share/Lumina-DE/i18n/lumina-info_cy.qm
/usr/local/share/Lumina-DE/i18n/lumina-info_da.qm
/usr/local/share/Lumina-DE/i18n/lumina-info_de.qm
/usr/local/share/Lumina-DE/i18n/lumina-info_el.qm
/usr/local/share/Lumina-DE/i18n/lumina-info_en_GB.qm
/usr/local/share/Lumina-DE/i18n/lumina-info_en_ZA.qm
/usr/local/share/Lumina-DE/i18n/lumina-info_es.qm
/usr/local/share/Lumina-DE/i18n/lumina-info_et.qm
/usr/local/share/Lumina-DE/i18n/lumina-info_eu.qm
/usr/local/share/Lumina-DE/i18n/lumina-info_fa.qm
/usr/local/share/Lumina-DE/i18n/lumina-info_fi.qm
/usr/local/share/Lumina-DE/i18n/lumina-info_fr.qm
/usr/local/share/Lumina-DE/i18n/lumina-info_fr_CA.qm
/usr/local/share/Lumina-DE/i18n/lumina-info_gl.qm
/usr/local/share/Lumina-DE/i18n/lumina-info_he.qm
/usr/local/share/Lumina-DE/i18n/lumina-info_hi.qm
/usr/local/share/Lumina-DE/i18n/lumina-info_hr.qm
/usr/local/share/Lumina-DE/i18n/lumina-info_hu.qm
/usr/local/share/Lumina-DE/i18n/lumina-info_id.qm
/usr/local/share/Lumina-DE/i18n/lumina-info_is.qm
/usr/local/share/Lumina-DE/i18n/lumina-info_it.qm
/usr/local/share/Lumina-DE/i18n/lumina-info_ja.qm
/usr/local/share/Lumina-DE/i18n/lumina-info_ka.qm
/usr/local/share/Lumina-DE/i18n/lumina-info_ko.qm
/usr/local/share/Lumina-DE/i18n/lumina-info_lt.qm
/usr/local/share/Lumina-DE/i18n/lumina-info_lv.qm
/usr/local/share/Lumina-DE/i18n/lumina-info_mk.qm
/usr/local/share/Lumina-DE/i18n/lumina-info_mn.qm
/usr/local/share/Lumina-DE/i18n/lumina-info_ms.qm
/usr/local/share/Lumina-DE/i18n/lumina-info_mt.qm
/usr/local/share/Lumina-DE/i18n/lumina-info_nb.qm
/usr/local/share/Lumina-DE/i18n/lumina-info_nl.qm
/usr/local/share/Lumina-DE/i18n/lumina-info_pa.qm
/usr/local/share/Lumina-DE/i18n/lumina-info_pl.qm
/usr/local/share/Lumina-DE/i18n/lumina-info_pt.qm
/usr/local/share/Lumina-DE/i18n/lumina-info_pt_BR.qm
/usr/local/share/Lumina-DE/i18n/lumina-info_ro.qm
/usr/local/share/Lumina-DE/i18n/lumina-info_ru.qm
/usr/local/share/Lumina-DE/i18n/lumina-info_sk.qm
/usr/local/share/Lumina-DE/i18n/lumina-info_sl.qm
/usr/local/share/Lumina-DE/i18n/lumina-info_sr.qm
/usr/local/share/Lumina-DE/i18n/lumina-info_sv.qm
/usr/local/share/Lumina-DE/i18n/lumina-info_sw.qm
/usr/local/share/Lumina-DE/i18n/lumina-info_ta.qm
/usr/local/share/Lumina-DE/i18n/lumina-info_tg.qm
/usr/local/share/Lumina-DE/i18n/lumina-info_th.qm
/usr/local/share/Lumina-DE/i18n/lumina-info_tr.qm
/usr/local/share/Lumina-DE/i18n/lumina-info_uk.qm
/usr/local/share/Lumina-DE/i18n/lumina-info_uz.qm
/usr/local/share/Lumina-DE/i18n/lumina-info_vi.qm
/usr/local/share/Lumina-DE/i18n/lumina-info_zh_CN.qm
/usr/local/share/Lumina-DE/i18n/lumina-info_zh_HK.qm
/usr/local/share/Lumina-DE/i18n/lumina-info_zh_TW.qm
/usr/local/share/Lumina-DE/i18n/lumina-info_zu.qm
/usr/local/share/Lumina-DE/i18n/lumina-open_af.qm
/usr/local/share/Lumina-DE/i18n/lumina-open_ar.qm
/usr/local/share/Lumina-DE/i18n/lumina-open_az.qm
/usr/local/share/Lumina-DE/i18n/lumina-open_bg.qm
/usr/local/share/Lumina-DE/i18n/lumina-open_bn.qm
/usr/local/share/Lumina-DE/i18n/lumina-open_bs.qm
/usr/local/share/Lumina-DE/i18n/lumina-open_ca.qm
/usr/local/share/Lumina-DE/i18n/lumina-open_cs.qm
/usr/local/share/Lumina-DE/i18n/lumina-open_cy.qm
/usr/local/share/Lumina-DE/i18n/lumina-open_da.qm
/usr/local/share/Lumina-DE/i18n/lumina-open_de.qm
/usr/local/share/Lumina-DE/i18n/lumina-open_el.qm
/usr/local/share/Lumina-DE/i18n/lumina-open_en_GB.qm
/usr/local/share/Lumina-DE/i18n/lumina-open_en_ZA.qm
/usr/local/share/Lumina-DE/i18n/lumina-open_es.qm
/usr/local/share/Lumina-DE/i18n/lumina-open_et.qm
/usr/local/share/Lumina-DE/i18n/lumina-open_eu.qm
/usr/local/share/Lumina-DE/i18n/lumina-open_fa.qm
/usr/local/share/Lumina-DE/i18n/lumina-open_fi.qm
/usr/local/share/Lumina-DE/i18n/lumina-open_fr.qm
/usr/local/share/Lumina-DE/i18n/lumina-open_fr_CA.qm
/usr/local/share/Lumina-DE/i18n/lumina-open_gl.qm
/usr/local/share/Lumina-DE/i18n/lumina-open_he.qm
/usr/local/share/Lumina-DE/i18n/lumina-open_hi.qm
/usr/local/share/Lumina-DE/i18n/lumina-open_hr.qm
/usr/local/share/Lumina-DE/i18n/lumina-open_hu.qm
/usr/local/share/Lumina-DE/i18n/lumina-open_id.qm
/usr/local/share/Lumina-DE/i18n/lumina-open_is.qm
/usr/local/share/Lumina-DE/i18n/lumina-open_it.qm
/usr/local/share/Lumina-DE/i18n/lumina-open_ja.qm
/usr/local/share/Lumina-DE/i18n/lumina-open_ka.qm
/usr/local/share/Lumina-DE/i18n/lumina-open_ko.qm
/usr/local/share/Lumina-DE/i18n/lumina-open_lt.qm
/usr/local/share/Lumina-DE/i18n/lumina-open_lv.qm
/usr/local/share/Lumina-DE/i18n/lumina-open_mk.qm
/usr/local/share/Lumina-DE/i18n/lumina-open_mn.qm
/usr/local/share/Lumina-DE/i18n/lumina-open_ms.qm
/usr/local/share/Lumina-DE/i18n/lumina-open_mt.qm
/usr/local/share/Lumina-DE/i18n/lumina-open_nb.qm
/usr/local/share/Lumina-DE/i18n/lumina-open_nl.qm
/usr/local/share/Lumina-DE/i18n/lumina-open_pa.qm
/usr/local/share/Lumina-DE/i18n/lumina-open_pl.qm
/usr/local/share/Lumina-DE/i18n/lumina-open_pt.qm
/usr/local/share/Lumina-DE/i18n/lumina-open_pt_BR.qm
/usr/local/share/Lumina-DE/i18n/lumina-open_ro.qm
/usr/local/share/Lumina-DE/i18n/lumina-open_ru.qm
/usr/local/share/Lumina-DE/i18n/lumina-open_sk.qm
/usr/local/share/Lumina-DE/i18n/lumina-open_sl.qm
/usr/local/share/Lumina-DE/i18n/lumina-open_sr.qm
/usr/local/share/Lumina-DE/i18n/lumina-open_sv.qm
/usr/local/share/Lumina-DE/i18n/lumina-open_sw.qm
/usr/local/share/Lumina-DE/i18n/lumina-open_ta.qm
/usr/local/share/Lumina-DE/i18n/lumina-open_tg.qm
/usr/local/share/Lumina-DE/i18n/lumina-open_th.qm
/usr/local/share/Lumina-DE/i18n/lumina-open_tr.qm
/usr/local/share/Lumina-DE/i18n/lumina-open_uk.qm
/usr/local/share/Lumina-DE/i18n/lumina-open_uz.qm
/usr/local/share/Lumina-DE/i18n/lumina-open_vi.qm
/usr/local/share/Lumina-DE/i18n/lumina-open_zh_CN.qm
/usr/local/share/Lumina-DE/i18n/lumina-open_zh_HK.qm
/usr/local/share/Lumina-DE/i18n/lumina-open_zh_TW.qm
/usr/local/share/Lumina-DE/i18n/lumina-open_zu.qm
/usr/local/share/Lumina-DE/i18n/lumina-screenshot_af.qm
/usr/local/share/Lumina-DE/i18n/lumina-screenshot_ar.qm
/usr/local/share/Lumina-DE/i18n/lumina-screenshot_az.qm
/usr/local/share/Lumina-DE/i18n/lumina-screenshot_bg.qm
/usr/local/share/Lumina-DE/i18n/lumina-screenshot_bn.qm
/usr/local/share/Lumina-DE/i18n/lumina-screenshot_bs.qm
/usr/local/share/Lumina-DE/i18n/lumina-screenshot_ca.qm
/usr/local/share/Lumina-DE/i18n/lumina-screenshot_cs.qm
/usr/local/share/Lumina-DE/i18n/lumina-screenshot_cy.qm
/usr/local/share/Lumina-DE/i18n/lumina-screenshot_da.qm
/usr/local/share/Lumina-DE/i18n/lumina-screenshot_de.qm
/usr/local/share/Lumina-DE/i18n/lumina-screenshot_el.qm
/usr/local/share/Lumina-DE/i18n/lumina-screenshot_en_GB.qm
/usr/local/share/Lumina-DE/i18n/lumina-screenshot_en_ZA.qm
/usr/local/share/Lumina-DE/i18n/lumina-screenshot_es.qm
/usr/local/share/Lumina-DE/i18n/lumina-screenshot_et.qm
/usr/local/share/Lumina-DE/i18n/lumina-screenshot_eu.qm
/usr/local/share/Lumina-DE/i18n/lumina-screenshot_fa.qm
/usr/local/share/Lumina-DE/i18n/lumina-screenshot_fi.qm
/usr/local/share/Lumina-DE/i18n/lumina-screenshot_fr.qm
/usr/local/share/Lumina-DE/i18n/lumina-screenshot_fr_CA.qm
/usr/local/share/Lumina-DE/i18n/lumina-screenshot_gl.qm
/usr/local/share/Lumina-DE/i18n/lumina-screenshot_he.qm
/usr/local/share/Lumina-DE/i18n/lumina-screenshot_hi.qm
/usr/local/share/Lumina-DE/i18n/lumina-screenshot_hr.qm
/usr/local/share/Lumina-DE/i18n/lumina-screenshot_hu.qm
/usr/local/share/Lumina-DE/i18n/lumina-screenshot_id.qm
/usr/local/share/Lumina-DE/i18n/lumina-screenshot_is.qm
/usr/local/share/Lumina-DE/i18n/lumina-screenshot_it.qm
/usr/local/share/Lumina-DE/i18n/lumina-screenshot_ja.qm
/usr/local/share/Lumina-DE/i18n/lumina-screenshot_ka.qm
/usr/local/share/Lumina-DE/i18n/lumina-screenshot_ko.qm
/usr/local/share/Lumina-DE/i18n/lumina-screenshot_lt.qm
/usr/local/share/Lumina-DE/i18n/lumina-screenshot_lv.qm
/usr/local/share/Lumina-DE/i18n/lumina-screenshot_mk.qm
/usr/local/share/Lumina-DE/i18n/lumina-screenshot_mn.qm
/usr/local/share/Lumina-DE/i18n/lumina-screenshot_ms.qm
/usr/local/share/Lumina-DE/i18n/lumina-screenshot_mt.qm
/usr/local/share/Lumina-DE/i18n/lumina-screenshot_nb.qm
/usr/local/share/Lumina-DE/i18n/lumina-screenshot_nl.qm
/usr/local/share/Lumina-DE/i18n/lumina-screenshot_pa.qm
/usr/local/share/Lumina-DE/i18n/lumina-screenshot_pl.qm
/usr/local/share/Lumina-DE/i18n/lumina-screenshot_pt.qm
/usr/local/share/Lumina-DE/i18n/lumina-screenshot_pt_BR.qm
/usr/local/share/Lumina-DE/i18n/lumina-screenshot_ro.qm
/usr/local/share/Lumina-DE/i18n/lumina-screenshot_ru.qm
/usr/local/share/Lumina-DE/i18n/lumina-screenshot_sk.qm
/usr/local/share/Lumina-DE/i18n/lumina-screenshot_sl.qm
/usr/local/share/Lumina-DE/i18n/lumina-screenshot_sr.qm
/usr/local/share/Lumina-DE/i18n/lumina-screenshot_sv.qm
/usr/local/share/Lumina-DE/i18n/lumina-screenshot_sw.qm
/usr/local/share/Lumina-DE/i18n/lumina-screenshot_ta.qm
/usr/local/share/Lumina-DE/i18n/lumina-screenshot_tg.qm
/usr/local/share/Lumina-DE/i18n/lumina-screenshot_th.qm
/usr/local/share/Lumina-DE/i18n/lumina-screenshot_tr.qm
/usr/local/share/Lumina-DE/i18n/lumina-screenshot_uk.qm
/usr/local/share/Lumina-DE/i18n/lumina-screenshot_uz.qm
/usr/local/share/Lumina-DE/i18n/lumina-screenshot_vi.qm
/usr/local/share/Lumina-DE/i18n/lumina-screenshot_zh_CN.qm
/usr/local/share/Lumina-DE/i18n/lumina-screenshot_zh_HK.qm
/usr/local/share/Lumina-DE/i18n/lumina-screenshot_zh_TW.qm
/usr/local/share/Lumina-DE/i18n/lumina-screenshot_zu.qm
/usr/local/share/Lumina-DE/i18n/lumina-search_af.qm
/usr/local/share/Lumina-DE/i18n/lumina-search_ar.qm
/usr/local/share/Lumina-DE/i18n/lumina-search_az.qm
/usr/local/share/Lumina-DE/i18n/lumina-search_bg.qm
/usr/local/share/Lumina-DE/i18n/lumina-search_bn.qm
/usr/local/share/Lumina-DE/i18n/lumina-search_bs.qm
/usr/local/share/Lumina-DE/i18n/lumina-search_ca.qm
/usr/local/share/Lumina-DE/i18n/lumina-search_cs.qm
/usr/local/share/Lumina-DE/i18n/lumina-search_cy.qm
/usr/local/share/Lumina-DE/i18n/lumina-search_da.qm
/usr/local/share/Lumina-DE/i18n/lumina-search_de.qm
/usr/local/share/Lumina-DE/i18n/lumina-search_el.qm
/usr/local/share/Lumina-DE/i18n/lumina-search_en_GB.qm
/usr/local/share/Lumina-DE/i18n/lumina-search_en_ZA.qm
/usr/local/share/Lumina-DE/i18n/lumina-search_es.qm
/usr/local/share/Lumina-DE/i18n/lumina-search_et.qm
/usr/local/share/Lumina-DE/i18n/lumina-search_eu.qm
/usr/local/share/Lumina-DE/i18n/lumina-search_fa.qm
/usr/local/share/Lumina-DE/i18n/lumina-search_fi.qm
/usr/local/share/Lumina-DE/i18n/lumina-search_fr.qm
/usr/local/share/Lumina-DE/i18n/lumina-search_fr_CA.qm
/usr/local/share/Lumina-DE/i18n/lumina-search_gl.qm
/usr/local/share/Lumina-DE/i18n/lumina-search_he.qm
/usr/local/share/Lumina-DE/i18n/lumina-search_hi.qm
/usr/local/share/Lumina-DE/i18n/lumina-search_hr.qm
/usr/local/share/Lumina-DE/i18n/lumina-search_hu.qm
/usr/local/share/Lumina-DE/i18n/lumina-search_id.qm
/usr/local/share/Lumina-DE/i18n/lumina-search_is.qm
/usr/local/share/Lumina-DE/i18n/lumina-search_it.qm
/usr/local/share/Lumina-DE/i18n/lumina-search_ja.qm
/usr/local/share/Lumina-DE/i18n/lumina-search_ka.qm
/usr/local/share/Lumina-DE/i18n/lumina-search_ko.qm
/usr/local/share/Lumina-DE/i18n/lumina-search_lt.qm
/usr/local/share/Lumina-DE/i18n/lumina-search_lv.qm
/usr/local/share/Lumina-DE/i18n/lumina-search_mk.qm
/usr/local/share/Lumina-DE/i18n/lumina-search_mn.qm
/usr/local/share/Lumina-DE/i18n/lumina-search_ms.qm
/usr/local/share/Lumina-DE/i18n/lumina-search_mt.qm
/usr/local/share/Lumina-DE/i18n/lumina-search_nb.qm
/usr/local/share/Lumina-DE/i18n/lumina-search_nl.qm
/usr/local/share/Lumina-DE/i18n/lumina-search_pa.qm
/usr/local/share/Lumina-DE/i18n/lumina-search_pl.qm
/usr/local/share/Lumina-DE/i18n/lumina-search_pt.qm
/usr/local/share/Lumina-DE/i18n/lumina-search_pt_BR.qm
/usr/local/share/Lumina-DE/i18n/lumina-search_ro.qm
/usr/local/share/Lumina-DE/i18n/lumina-search_ru.qm
/usr/local/share/Lumina-DE/i18n/lumina-search_sk.qm
/usr/local/share/Lumina-DE/i18n/lumina-search_sl.qm
/usr/local/share/Lumina-DE/i18n/lumina-search_sr.qm
/usr/local/share/Lumina-DE/i18n/lumina-search_sv.qm
/usr/local/share/Lumina-DE/i18n/lumina-search_sw.qm
/usr/local/share/Lumina-DE/i18n/lumina-search_ta.qm
/usr/local/share/Lumina-DE/i18n/lumina-search_tg.qm
/usr/local/share/Lumina-DE/i18n/lumina-search_th.qm
/usr/local/share/Lumina-DE/i18n/lumina-search_tr.qm
/usr/local/share/Lumina-DE/i18n/lumina-search_uk.qm
/usr/local/share/Lumina-DE/i18n/lumina-search_uz.qm
/usr/local/share/Lumina-DE/i18n/lumina-search_vi.qm
/usr/local/share/Lumina-DE/i18n/lumina-search_zh_CN.qm
/usr/local/share/Lumina-DE/i18n/lumina-search_zh_HK.qm
/usr/local/share/Lumina-DE/i18n/lumina-search_zh_TW.qm
/usr/local/share/Lumina-DE/i18n/lumina-search_zu.qm
/usr/local/share/Lumina-DE/i18n/lumina-xconfig_af.qm
/usr/local/share/Lumina-DE/i18n/lumina-xconfig_ar.qm
/usr/local/share/Lumina-DE/i18n/lumina-xconfig_az.qm
/usr/local/share/Lumina-DE/i18n/lumina-xconfig_bg.qm
/usr/local/share/Lumina-DE/i18n/lumina-xconfig_bn.qm
/usr/local/share/Lumina-DE/i18n/lumina-xconfig_bs.qm
/usr/local/share/Lumina-DE/i18n/lumina-xconfig_ca.qm
/usr/local/share/Lumina-DE/i18n/lumina-xconfig_cs.qm
/usr/local/share/Lumina-DE/i18n/lumina-xconfig_cy.qm
/usr/local/share/Lumina-DE/i18n/lumina-xconfig_da.qm
/usr/local/share/Lumina-DE/i18n/lumina-xconfig_de.qm
/usr/local/share/Lumina-DE/i18n/lumina-xconfig_el.qm
/usr/local/share/Lumina-DE/i18n/lumina-xconfig_en_GB.qm
/usr/local/share/Lumina-DE/i18n/lumina-xconfig_en_ZA.qm
/usr/local/share/Lumina-DE/i18n/lumina-xconfig_es.qm
/usr/local/share/Lumina-DE/i18n/lumina-xconfig_et.qm
/usr/local/share/Lumina-DE/i18n/lumina-xconfig_eu.qm
/usr/local/share/Lumina-DE/i18n/lumina-xconfig_fa.qm
/usr/local/share/Lumina-DE/i18n/lumina-xconfig_fi.qm
/usr/local/share/Lumina-DE/i18n/lumina-xconfig_fr.qm
/usr/local/share/Lumina-DE/i18n/lumina-xconfig_fr_CA.qm
/usr/local/share/Lumina-DE/i18n/lumina-xconfig_gl.qm
/usr/local/share/Lumina-DE/i18n/lumina-xconfig_he.qm
/usr/local/share/Lumina-DE/i18n/lumina-xconfig_hi.qm
/usr/local/share/Lumina-DE/i18n/lumina-xconfig_hr.qm
/usr/local/share/Lumina-DE/i18n/lumina-xconfig_hu.qm
/usr/local/share/Lumina-DE/i18n/lumina-xconfig_id.qm
/usr/local/share/Lumina-DE/i18n/lumina-xconfig_is.qm
/usr/local/share/Lumina-DE/i18n/lumina-xconfig_it.qm
/usr/local/share/Lumina-DE/i18n/lumina-xconfig_ja.qm
/usr/local/share/Lumina-DE/i18n/lumina-xconfig_ka.qm
/usr/local/share/Lumina-DE/i18n/lumina-xconfig_ko.qm
/usr/local/share/Lumina-DE/i18n/lumina-xconfig_lt.qm
/usr/local/share/Lumina-DE/i18n/lumina-xconfig_lv.qm
/usr/local/share/Lumina-DE/i18n/lumina-xconfig_mk.qm
/usr/local/share/Lumina-DE/i18n/lumina-xconfig_mn.qm
/usr/local/share/Lumina-DE/i18n/lumina-xconfig_ms.qm
/usr/local/share/Lumina-DE/i18n/lumina-xconfig_mt.qm
/usr/local/share/Lumina-DE/i18n/lumina-xconfig_nb.qm
/usr/local/share/Lumina-DE/i18n/lumina-xconfig_nl.qm
/usr/local/share/Lumina-DE/i18n/lumina-xconfig_pa.qm
/usr/local/share/Lumina-DE/i18n/lumina-xconfig_pl.qm
/usr/local/share/Lumina-DE/i18n/lumina-xconfig_pt.qm
/usr/local/share/Lumina-DE/i18n/lumina-xconfig_pt_BR.qm
/usr/local/share/Lumina-DE/i18n/lumina-xconfig_ro.qm
/usr/local/share/Lumina-DE/i18n/lumina-xconfig_ru.qm
/usr/local/share/Lumina-DE/i18n/lumina-xconfig_sk.qm
/usr/local/share/Lumina-DE/i18n/lumina-xconfig_sl.qm
/usr/local/share/Lumina-DE/i18n/lumina-xconfig_sr.qm
/usr/local/share/Lumina-DE/i18n/lumina-xconfig_sv.qm
/usr/local/share/Lumina-DE/i18n/lumina-xconfig_sw.qm
/usr/local/share/Lumina-DE/i18n/lumina-xconfig_ta.qm
/usr/local/share/Lumina-DE/i18n/lumina-xconfig_tg.qm
/usr/local/share/Lumina-DE/i18n/lumina-xconfig_th.qm
/usr/local/share/Lumina-DE/i18n/lumina-xconfig_tr.qm
/usr/local/share/Lumina-DE/i18n/lumina-xconfig_uk.qm
/usr/local/share/Lumina-DE/i18n/lumina-xconfig_uz.qm
/usr/local/share/Lumina-DE/i18n/lumina-xconfig_vi.qm
/usr/local/share/Lumina-DE/i18n/lumina-xconfig_zh_CN.qm
/usr/local/share/Lumina-DE/i18n/lumina-xconfig_zh_HK.qm
/usr/local/share/Lumina-DE/i18n/lumina-xconfig_zh_TW.qm
/usr/local/share/Lumina-DE/i18n/lumina-xconfig_zu.qm

%changelog
* Thu Jul 30 2015 Jesse Smith jsmith@resonatingmedia.com
- Initial build
