.Dd October 30, 2017
.Dt LUMINA-CALCULATOR 8
.Os 1.3.3

.Sh NAME
.Nm lumina-calculator
.Nd full scientific calculator with a simple interface.

.Sh SYNOPSIS
.Nm

.Sh DESCRIPTION
.Nm
is a simple scientific calculator interface.
It has exponential, trigonometric, and
logarithmic functions.
It can also calculate percentages, square roots, and hyperbolic
trigonometric functions.
The utility keeps a history of previous calculations.
This history can be saved as a .txt file.

.Sh FILES
.Bl -tag -width indent
.It Pa /usr/local/bin/lumina-calculator
.El

.Sh AUTHORS
.An Aaron St. John and Tim Moore
.Aq aaron@ixsystems.com
