.Dd October 23, 2017
.Dt LUMINA-XDG-ENTRY 8
.Os 1.3.3

.Sh NAME
.Nm lumina-xdg-entry
.Nd is a simple graphical tool for creating XDG desktop entries.

.Sh SYNOPSIS
.Nm

.Sh DESCRIPTION
The
.Nm
command brings up the graphical tool to create desktop entries.
The user can create an XDG desktop with a specified name and generic name.

.Sh AUTHORS
.An Aaron St. John
.Aq aaron@ixsystems.com
