.Dd November 7, 2017
.Dt LUMINA-INFO 8
.Os 1.3.3

.Sh NAME
.Nm lumina-info
.Nd view information about the current desktop.

.Sh SYNOPSIS
.Nm

.Sh DESCRIPTION
.Nm
opens a graphical interface about: general information, license
information, and acknowledgements.
General information includes: desktop version, OS build, and an option
to view the Qt version.

.Sh FILES
.Bl -tag -width indent
.It Pa /usr/local/bin/lumina-info
.El

.Sh AUTHORS
.An Aaron St. John and Tim Moore
.Aq aaron@ixsystems.com
