.Dd November 2, 2017
.Dt LUMINA-SCREENSHOT 8
.Os 1.3.3

.Sh NAME
.Nm lumina-screenshot
.Nd a utility to take and save screenshots of the desktop.

.Sh SYNOPSIS
.Nm

.Sh DESCRIPTION
.Nm
opens the graphical utility and takes a screenshot.
Then, it can view, crop, zoom, and save the screenshot.
There is also an option to open the screenshot with a different
application.
There are options to capture the entire session, a single
screen, a single window, or a selected area.
By default, the utility is bound to the "PrintScreen" keyboard button.

.Sh FILES
.Bl -tag -width indent
.It Pa /usr/local/bin/lumina-screenshot
.El

.Sh AUTHORS
.An Aaron St. John and Tim Moore
.Aq aaron@ixsystems.com
