# Created by: Ken Moore <ken@pcbsd.org>
# $FreeBSD$

PORTNAME=	lumina
PORTVERSION=	%%CHGVERSION%%
PORTREVISION=	%%CHGREVISION%%
PORTEPOCH=	3
CATEGORIES=	x11

MAINTAINER=	kmoore@FreeBSD.org
COMMENT=	Lumina Desktop Environment (meta-port)

LICENSE=	BSD3CLAUSE

RUN_DEPENDS=	lumina-desktop:x11/lumina-core \
		lumina-config:x11/lumina-coreutils \
		lumina-archiver:deskutils/lumina-archiver \
		lumina-calculator:deskutils/lumina-calculator \
		lumina-fileinfo:deskutils/lumina-fileinfo \
		lumina-fm:deskutils/lumina-fm \
		lumina-mediaplayer:deskutils/lumina-mediaplayer \
		lumina-notify:deskutils/lumina-notify \
		lumina-screenshot:deskutils/lumina-screenshot \
		lumina-textedit:deskutils/lumina-textedit \
		lumina-xdg-entry:deskutils/lumina-xdg-entry

CONFLICTS=	lumina-devel-0*

USES=		metaport

.include <bsd.port.mk>
